#' Visualize the 3'end APA changes between the two groups
#' 
#' This function loads a gtf file and extract necessary information of each gene from it.
#' @param CSH_data CSH data generated by CSH_profile function
#' @param P_cutoff adjusted P value cutoff to be considered as significant change
#' @param delta distance between two samples to be considered as significant APA events
#' @return a data frame showing the significant APA change between sample1 and sample2


CSH_plot <- function(CSH_data,P_cutoff=0.05,delta=0.1){
  CSH_table <- CSH_data
  CS_shift_col <- colnames(CSH_table)[grepl("^CS_shift", colnames(CSH_table))]
  CSH_table$P_adj <-p.adjust(CSH_table$pvalue, method = "fdr")
  CSH_table$Col <- "gray"
  CSH_table$Vol_P <- (-log10(CSH_table$P_adj))
  CSH_table[Vol_P == Inf, Vol_P := (max(-log10(CSH_table[P_adj!=0]$P_adj))+0.1)]
  CSH_table$CS_shift_trend <- "no change"
  setnames(CSH_table, old = CS_shift_col, new = "CS_shift")
  CSH_table[(P_adj < P_cutoff & CS_shift > delta), Col := "red"]
  CSH_table[(P_adj < P_cutoff & CS_shift > delta), CS_shift_trend := "Downstream"]
  CSH_table[(P_adj < P_cutoff & CS_shift < -delta), Col := "blue"]
  CSH_table[(P_adj < P_cutoff & CS_shift < -delta), CS_shift_trend := "Upstream"]
  shortening <- length(subset(CSH_table,Col=="blue")$gene_id)
  lengthening <- length(subset(CSH_table,Col=="red")$gene_id)
  all <- length(CSH_table$gene_id)
#  pdf("APA_plot.pdf",7,7)
  par(mar = c(6, 5, 4, 3) + 0.1)
  plot(x=CSH_table$CS_shift,  y=CSH_table$Vol_P, xlim=c(-1,1), 
       pch= 20, sub = paste(shortening,"toward Upstream","and",lengthening,"toward Downstream" ,"in all", all, "PASs",sep=" "),
       xlab = paste0(CS_shift_col, sep=""),  ylab = "-log10(adjusted p value)",  col = CSH_table$Col, cex=0.7)
  abline(v = c(-delta,delta), col = "green", lty = 2, lwd = 2)
  abline(h=(-log10(P_cutoff)), col = "green", lty = 2, lwd = 2)
#  dev.off()
  setnames(CSH_table, old = "CS_shift", new = CS_shift_col)
  return(CSH_table[, !c("Col","Vol_P"), with = FALSE])
}